{
 "title": "Donnes de Scraping",
 "description": "On visualise quelques pannels qui nous donnent des informations sur le scaping de Prometheus",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": " nombre d'échantillons (samples) après l'application des règles de relabeling",
   "type": "timeseries",
   "description": "Lorsque Prometheus récupère les métriques d'une cible (par exemple, votre application FastAPI), il peut appliquer des règles de relabeling pour modifier ou filtrer les métriques avant de les stocker. Cela peut inclure des actions telles que le renommage d'étiquettes, le filtrage de certaines métriques, ou d'autres transformations.\n\nLa métrique scrape_samples_post_metric_relabeling mesure le nombre d'échantillons après l'application de ces règles de relabeling. Elle peut être utile pour comprendre comment les règles de relabeling affectent le nombre final d'échantillons qui sont effectivement stockés dans Prometheus.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "scrape_samples_post_metric_relabeling",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nombre de Séries Ajoutées",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "scrape_series_added", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nombre d'Échantillons Scannés",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "scrape_samples_scraped", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Duree de scaping ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "scrape_duration_seconds", "legendFormat": "__auto" }
   ]
  }
 ]
}