apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    access: proxy
    editable: true

  - name: Consommation
    folder: "yak-dashboards"
    type: "file"
    options:
      path: "/var/lib/grafana/Dashboards"

  # new datasource for FastAPI metrics
  - name: FastAPI Metrics
    type: prometheus
    url: http://fastapi:5000
    access: proxy
    editable: true
