apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    access: proxy
    editable: true

  # new datasource for FastAPI metrics
  - name: FastAPI Metrics
    type: prometheus
    url: http://fastapi:5000
    access: proxy
    editable: true
